"""SOAP Note Generator — creates structured clinical documentation."""

import json
import os
from datetime import datetime

ICD_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "data", "icd10_codes.json")


def _load_icd10():
    with open(ICD_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


async def handle_soap_note(args: dict) -> dict:
    """
    Generate a structured SOAP (Subjective, Objective, Assessment, Plan) note.
    """
    subjective = args.get("subjective", "Not documented")
    objective = args.get("objective", "Triage assessment via voice — no physical exam performed")
    assessment = args.get("assessment", "Pending review")
    plan = args.get("plan", "Pending review")
    icd10_input = args.get("icd10_codes", [])

    # Resolve ICD-10 codes with descriptions
    icd_data = _load_icd10()
    resolved_codes = []
    for code in icd10_input:
        code_upper = code.upper()
        if code_upper in icd_data["codes"]:
            info = icd_data["codes"][code_upper]
            resolved_codes.append({
                "code": code_upper,
                "description": info["description"],
                "category": info["category"],
            })
        else:
            resolved_codes.append({
                "code": code_upper,
                "description": "Code not found in database",
                "category": "Unknown",
            })

    now = datetime.now()

    soap_note = {
        "document_type": "SOAP Note",
        "generated_by": "VoiceMed AI Triage System",
        "timestamp": now.isoformat(),
        "date": now.strftime("%B %d, %Y"),
        "time": now.strftime("%I:%M %p"),

        "subjective": {
            "title": "S — Subjective",
            "content": subjective,
            "description": "Patient's reported symptoms, history, and concerns",
        },
        "objective": {
            "title": "O — Objective",
            "content": objective,
            "description": "Observable/measurable data from the encounter",
        },
        "assessment": {
            "title": "A — Assessment",
            "content": assessment,
            "icd10_codes": resolved_codes,
            "description": "Clinical impression and possible conditions",
        },
        "plan": {
            "title": "P — Plan",
            "content": plan,
            "description": "Recommended next steps and follow-up care",
        },

        "disclaimer": "GENERATED BY AI — This note was generated by VoiceMed AI, an automated triage system. It is NOT a substitute for professional medical evaluation. All clinical decisions should be made by licensed healthcare providers.",

        "formatted_text": _format_soap_text(subjective, objective, assessment, plan, resolved_codes, now),
    }

    return soap_note


def _format_soap_text(subjective, objective, assessment, plan, codes, timestamp):
    """Create a plaintext formatted SOAP note."""
    lines = [
        "═══════════════════════════════════════════════════",
        "            VOICEMED AI — SOAP NOTE",
        f"            {timestamp.strftime('%B %d, %Y • %I:%M %p')}",
        "═══════════════════════════════════════════════════",
        "",
        "S — SUBJECTIVE",
        "───────────────────────────────────────────────────",
        subjective,
        "",
        "O — OBJECTIVE",
        "───────────────────────────────────────────────────",
        objective,
        "",
        "A — ASSESSMENT",
        "───────────────────────────────────────────────────",
        assessment,
    ]

    if codes:
        lines.append("")
        lines.append("ICD-10 Codes:")
        for c in codes:
            lines.append(f"  • {c['code']} — {c['description']}")

    lines.extend([
        "",
        "P — PLAN",
        "───────────────────────────────────────────────────",
        plan,
        "",
        "═══════════════════════════════════════════════════",
        "⚠️  AI-GENERATED — Not a substitute for professional",
        "    medical evaluation. Review by licensed provider",
        "    required before clinical use.",
        "═══════════════════════════════════════════════════",
    ])

    return "\n".join(lines)
